### ISSUE TITLE
DRY Code

### ISSUE THREAD

**Issue by LLaxt** [Quidditch-Queue-Handlers/FEC-Project-Atelier#63]
When you find yourself writing the same thing or similar multiple times, consider how you might DRY your code. For example, you could use a loop to increment 1-5. 

https://github.com/Quidditch-Queue-Handlers/FEC-Project-Atelier/blob/21a673651c1b6029488b6d71694363ad95f1beb3/client/src/components/RatingsAndReviews/ProductBreakdown.jsx#L6-L10

**Comment by squeakypickles33** [comment]
I fixed this with mapping the entries, thanks!
